"""KPI dictionary — activity / operational / financial / risk."""

KPIS = [
    # family, id, name, question, formula, source, owner, cadence, gaming_risk
    ("Activity", "ACT-01", "Invoices handled by agents", "How much volume did agents touch?", "Count of invoices with an agent decision in period", "Agent log", "A16 owner", "Daily", "Inflates if agents are set to 'touch' everything"),
    ("Activity", "ACT-02", "Exceptions handled", "How many exceptions did the workforce work?", "Count of exception tickets moved from New", "Exception store", "AP Manager", "Daily", "Opening and closing junk tickets"),
    ("Activity", "ACT-03", "Follow-ups sent", "How much chase activity occurred?", "Count of A08/A09 messages sent", "Comms log", "Supplier desk", "Weekly", "Spam nudges"),
    ("Operational", "OPS-01", "Straight-through processing rate", "What share posted with no human exception touch?", "STP invoices / invoices posted", "ERP + exception store", "AP Manager", "Weekly", "Reclassifying exceptions as 'comments'"),
    ("Operational", "OPS-02", "Exception rate", "What share of invoices excepted?", "Excepted invoices / invoices received", "Exception store", "AP Manager", "Weekly", "Not opening tickets"),
    ("Operational", "OPS-03", "Classification accuracy", "How often is the taxonomy code right?", "QA-agreed codes / QA sample", "QA sample (min 100/month at scale)", "AP Quality", "Monthly", "Sampling only easy items"),
    ("Operational", "OPS-04", "Extraction accuracy", "Are header and line fields correct vs source?", "Correct fields / fields sampled (header and lines reported separately)", "QA vs source image", "Intake owner", "Weekly", "Header-only sampling"),
    ("Operational", "OPS-05", "Matching accuracy", "Are match decisions correct?", "Correct match decisions / sampled matches", "QA", "P2P owner", "Weekly", "Excluding multi-line"),
    ("Operational", "OPS-06", "False-positive rate", "How often do we flag a healthy item?", "False flags / flags", "QA", "Controls + AP Quality", "Monthly", "Raising thresholds silently"),
    ("Operational", "OPS-07", "False-negative rate", "How often do we miss a real defect?", "Missed defects / known defects (including injected test cases)", "QA + test harness", "Controls", "Monthly", "Not planting test defects"),
    ("Operational", "OPS-08", "Exception resolution rate", "What share of exceptions close in SLA?", "Closed in SLA / exceptions due", "Exception store", "AP Manager", "Weekly", "Closing as 'no action' "),
    ("Operational", "OPS-09", "Human intervention rate", "What share still needs a person?", "Invoices with human edit or decision / invoices", "Agent log", "A16 owner", "Weekly", "Hiding Level 3 writes as 'system'"),
    ("Operational", "OPS-10", "Average resolution time", "How long do exceptions live?", "Median hours, New → Closed", "Exception store", "AP Manager", "Weekly", "Reopening instead of keeping open"),
    ("Operational", "OPS-11", "Time to invoice posting", "How long from intake to posted?", "Median hours, Intake → Posted", "Intake + ERP", "AP Ops", "Weekly", "Parking outside the clock"),
    ("Operational", "OPS-12", "Repeat exception rate", "Are we fixing causes?", "Exceptions whose cause code recurred for same vendor/buyer in 8 weeks / exceptions", "A15 mart", "Process excellence", "Monthly", "New cause codes for old problems"),
    ("Operational", "OPS-13", "On-time supplier follow-up", "Did we chase on time?", "A08 sent on or before due / A08 due", "Comms log", "Supplier desk", "Weekly", "Sending empty templates"),
    ("Operational", "OPS-14", "On-time internal follow-up", "Did we chase owners on time?", "A09 sent on or before due / A09 due", "Comms log", "AP Team Lead", "Weekly", "Same as OPS-13"),
    ("Operational", "OPS-15", "Ageing — >30 day unresolved", "Is the backlog rotting?", "Open exceptions >30 days / open exceptions", "Exception store", "AP Manager", "Weekly", "Mass write-offs at month-end"),
    ("Operational", "OPS-16", "Payment-on-time rate", "Did we pay when we intended?", "Payments on or before due / payments (policy-due, not supplier-due if they differ)", "Payment register", "Treasury + AP", "Monthly", "Changing due dates"),
    ("Operational", "OPS-17", "Missing-receipt reduction", "Is GR discipline improving?", "Missing-GR count period-end vs baseline", "A05 register", "P2P owner", "Monthly", "Creating dummy GRs"),
    ("Operational", "OPS-18", "PO compliance", "Are invoices backed by a valid PO when policy requires?", "PO-compliant invoices / invoices in PO-required categories", "A06 + ERP", "Procurement ops", "Monthly", "Blanket-PO dumping"),
    ("Financial", "FIN-01", "Cost per invoice", "What does processing one invoice cost us?", "(AP fully loaded labour + AP tech + allocated overhead + AI/tool) / invoices posted", "Finance + AP", "Controller", "Monthly", "Moving people off the AP cost centre"),
    ("Financial", "FIN-02", "Cost per exception resolved", "What does an exception cost?", "Exception-handling labour + AI / exceptions closed", "Time study or roster + tickets", "AP Manager", "Monthly", "Not counting manager time"),
    ("Financial", "FIN-03", "AI inference cost", "What did the models and tools cost?", "Invoiced AI/tool spend in period", "Vendor invoices", "Finance systems", "Monthly", "Hiding spend in IT"),
    ("Financial", "FIN-04", "Cost per correct outcome", "What do we pay for a right answer?", "(AI + human review cost) / QA-correct decisions", "Cost + QA", "A16 owner", "Monthly", "Shrinking the QA sample"),
    ("Financial", "FIN-05", "Estimated human hours released", "How much capacity returned?", "Baseline minutes × volume × measured touch reduction / 60 — range, not a point", "Time study + volume", "Transformation", "Monthly", "Counting theoretical max"),
    ("Financial", "FIN-06", "Validated financial savings", "What savings survived finance challenge?", "Savings with a named Controller attestation in the period", "Benefits tracker", "Controller", "Quarterly", "Booking unverified 'soft' savings"),
    ("Financial", "FIN-07", "Early-payment discount captured", "Did we take discounts we intended?", "Discounts taken / discounts available under policy", "Payment register", "Treasury", "Monthly", "Taking discounts that fail the cost-of-cash test"),
    ("Financial", "FIN-08", "Late-payment cost", "What did lateness cost?", "Fees + documented commercial penalties + estimated relationship cost (labelled if estimated)", "AP + procurement", "Controller", "Quarterly", "Ignoring commercial penalties"),
    ("Risk", "RSK-01", "Control breaches", "Did we break a written control?", "Count of confirmed breaches (SoD, unauthorised send, bank-data write, payment release by agent)", "Incident log", "Controls", "Immediate / monthly", "Not logging"),
    ("Risk", "RSK-02", "Escalation rate", "How often do we need a senior human?", "Escalations / exceptions", "Exception store", "AP Manager", "Weekly", "Never escalating"),
    ("Risk", "RSK-03", "Audit exceptions", "What did internal/external audit find in AP/AI?", "Count and severity", "Audit tracker", "Controller", "Per audit", "Scoping AI out of the audit"),
    ("Risk", "RSK-04", "Rework rate", "How often is an agent output rejected?", "Rejected drafts or reversed decisions / outputs", "QA + workflow", "AP Quality", "Weekly", "Silent edits"),
    ("Risk", "RSK-05", "Override rate", "How often do humans override the agent?", "Overrides / agent decisions", "Agent log", "A16 owner", "Weekly", "High override can be healthy if the agent is new; watch the trend"),
    ("Risk", "RSK-06", "Injection / suspicious-input flags", "Are we seeing instruction-like content?", "Flags / invoices", "A01 log", "Controls + security", "Weekly", "Turning the detector off"),
    ("Risk", "RSK-07", "Duplicate payments prevented (confirmed)", "Did a human-confirmed stop avoid a second payment?", "Count of stopped items later confirmed duplicate", "A10 + A12 + payment", "Controls", "Monthly", "Counting every hold"),
    ("Risk", "RSK-08", "Unauthorised agent action", "Did an agent act above its level?", "Count — target 0", "Access + action log", "Controls", "Immediate", "Shared credentials"),
]
