export { ENGINE_VERSION, ENGINE_MAJOR_VERSION, METHOD_VERSION } from './version';
export { d, money, moneyString, rate, zero, max0 } from './money';
export { defaultMethodConfig, familyOf, checkQuestion } from './config';
export { runScan } from './run';
export { computeRunHash, findingId, sha256, hashBytes } from './hash';
export { allocateSellSide, runningMaxIdentity, SELL_PRIORITY } from './allocation';
export { buildLineEconomics, summariseWaterfall, lineEconomics } from './waterfall';
export { economicCoverage } from './coverage';
export { priceAction, restorePrice, breakEvenVolumeRetention } from './price-action';
export { marginIntegrityIndex } from './mii';
export { calibratedFactor } from './bankability';
export { customerSnapshots, customerRisk, riskBandFromScore } from './risk';
export * from './ingest/index';
export type * from './types';
export type { Finding } from '@marginshield/schemas';
